### ISSUE TITLE
C:\Users\vineethreddy\OneDrive\Desktop\ulanedet>python demo.py configs/culane.py --test_model culane_18.pth merge  test_model  config start testing... Traceback (most recent call last):   File "demo.py", line 48, in <module>     datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, split),img_transform = img_transforms) for split in splits]   File "demo.py", line 48, in <listcomp>     datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, split),img_transform = img_transforms) for split in splits]   File "C:\Users\vineethreddy\OneDrive\Desktop\ulanedet\data\dataset.py", line 19, in __init__     with open(list_path, 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'ulanedet\\CULANEROOT\\test0_normal.txt'

### ISSUE THREAD

**Issue by thummavineethreddy** [cfzd/Ultra-Fast-Lane-Detection#119]

**Comment by thummavineethreddy** [comment]
Even though I have the culaneroot  ,it is showing no such directory found in windows.

**Comment by cfzd** [comment]
@thummavineethreddy 
It seems your code is wrong. Your code is:
```
datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, split),img_transform = img_transforms) for split in splits]
```
while the code in our repository is:
```
datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms) for split in splits]
```

Please check and update your code.

**Comment by thummavineethreddy** [comment]
Thank you for an early reply. 
I'm getting the same error after updating the code as well.

**Comment by cfzd** [comment]
@thummavineethreddy 
Can you report the error log?
