### ISSUE TITLE
How do you arrange the directory of tusimple dataset ?

### ISSUE THREAD

**Issue by eeyrw** [cfzd/Ultra-Fast-Lane-Detection#12]
When I repeated the step converting tusimple dataset, some errors occured to me: 
```
Traceback (most recent call last):
  File "scripts/convert_tusimple.py", line 145, in <module>
    names,line_txt = get_tusimple_list(args.root,  ['label_data_0601.json','label_data_0531.json','label_data_0313.json'])
  File "scripts/convert_tusimple.py", line 45, in get_tusimple_list
    label_json = [json.loads(line) for line in open(l).readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '/data/home/xxxxx/dataset/tusimple/label_data_0601.json'
```
Then I tried to change the root dir to tusimple_root/train and it seemed to work and generate the train_gt.txt under the current director. But new error prompted out:
```
Traceback (most recent call last):
  File "scripts/convert_tusimple.py", line 150, in <module>
    names,line_txt = get_tusimple_list(args.root, ['test_tasks_0627.json'])
  File "scripts/convert_tusimple.py", line 45, in get_tusimple_list
    label_json = [json.loads(line) for line in open(l).readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '/data/home/xxxxx/dataset/tusimple/train_set/test_tasks_0627.json' 
```
Here is my directory arrangement of tusimple dataset:
```
.
├── test_baseline.json
├── test_label.json
├── test_set
│   ├── clips
│   │   ├── 0530
│   │   ├── 0531
│   │   └── 0601
│   ├── readme.md
│   └── test_tasks_0627.json
├── test_set.zip
├── train_set
│   ├── clips
│   │   ├── 0313-1
│   │   ├── 0313-2
│   │   ├── 0531
│   │   └── 0601
│   ├── label_data_0313.json
│   ├── label_data_0531.json
│   ├── label_data_0601.json
│   └── readme.md
├── train_set.zip
├── tusimple-benchmark
│   ├── doc
│   │   ├── lane_detection
│   │   └── velocity_estimation
│   ├── evaluate
│   │   ├── __init__.py
│   │   ├── lane.py
│   │   └── velocity.py
│   ├── example
│   │   ├── __init__.py
│   │   ├── lane_demo.ipynb
│   │   └── velocity_demo.ipynb
│   └── README.md
└── tusimple_dl.sh
```

**Comment by cfzd** [comment]
@eeyrw 
Hi, just unzip all things to the $TUSIMPLEROOT and it should work. Here is my directory arrangement:
```
$TUSIMPLEROOT
|──clips
|──label_data_0313.json
|──label_data_0531.json
|──label_data_0601.json
|──test_tasks_0627.json
|──test_label.json
|──readme.md
```

**Comment by eeyrw** [comment]
I see.
