### ISSUE TITLE
How to solve data type errors

### ISSUE THREAD

**Issue by XZQAN** [cfzd/Ultra-Fast-Lane-Detection#127]
0%|          | 0/227 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "E:/Desktop/Ultra-Fast-Lane-Detection-master/train.py", line 156, in <module>
    train(net, train_loader, loss_dict, optimizer, scheduler,logger, epoch, metric_dict, cfg.use_aux)
  File "E:/Desktop/Ultra-Fast-Lane-Detection-master/train.py", line 69, in train
    loss = calc_loss(loss_dict, results, logger, global_step)
  File "E:/Desktop/Ultra-Fast-Lane-Detection-master/train.py", line 46, in calc_loss
    loss_cur = loss_dict['op'][i](*datas)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Desktop\Ultra-Fast-Lane-Detection-master\utils\loss.py", line 37, in forward
    loss = self.nll(log_score, labels)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\loss.py", line 211, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\anaconda\lib\site-packages\torch\nn\functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss2d_forward

**Comment by cfzd** [comment]
@XZQAN 
I fixed this problem. Please update your code via `git pull`.

**Comment by XZQAN** [comment]
thanks for the early reply，
