### ISSUE TITLE
An error occurred while testing the Tusimple dataset

### ISSUE THREAD

**Issue by zhangzhengde0225** [cfzd/Ultra-Fast-Lane-Detection#14]
I've finished setting up and running test.py for Tusimple dataset, the console reports an error as follows:

```
start testing...
100%|█████████████████████████████████████████| 348/348 [00:39<00:00,  2.15it/s]
Traceback (most recent call last):
  File "/home/zzd/PycharmProject/SHNAVI/moving_car/UFLD/test.py", line 48, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "/home/zzd/PycharmProject/SHNAVI/moving_car/UFLD/evaluation/eval_wrapper.py", line 163, in eval_lane
    os.path.join(data_root, 'test_label.json'))
  File "/home/zzd/PycharmProject/SHNAVI/moving_car/UFLD/evaluation/tusimple/lane.py", line 61, in bench_one_submit
    json_gt = [json.loads(line) for line in open(gt_file).readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '/home/zzd/workplace/TuSimple/test_set/test_label.json'
```

It point out that the file "test_lable.json" is missing.
I ran "script/convert_ tusimple.py" and checked the "test_set" folder,  there is no such file indeed.
I want to know how the file was obtained?

**Comment by cfzd** [comment]
@zhangzhengde0225 
Hi, you can download the `test_label.json` from [here](https://github.com/TuSimple/tusimple-benchmark/issues/3).

**Comment by littleserendipity** [comment]
@cfzd First i input the code `python demo.py configs/culane.py --test_model E:/LaneCode/Ultra-Fast-Lane-Detection/culane_18.pth` to terminal.It works correctly,which outputs test0_normal.avi~test8_night.avi one by one successfully.
Then i input the code `python demo.py configs/tusimple.py --test_model E:/LaneCode/Ultr
a-Fast-Lane-Detection/tusimple_18.pth`into the terminal,Output error as follows: 
`merge  test_model  config
start testing...
test0_normal.avi
  0%|                                                                                 | 0/9621 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 88, in <module>
    for i, data in enumerate(tqdm.tqdm(loader)):
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\tqdm\std.py", line 1130, in __iter__
    for obj in iterable:
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data

    data.reraise()
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_lo
op
    data = fetcher.fetch(index)
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\LaneCode\Ultra-Fast-Lane-Detection\data\dataset.py", line 27, in __getitem__
    img = loader_func(img_path)
  File "E:\LaneCode\Ultra-Fast-Lane-Detection\data\dataset.py", line 11, in loader_func
    return Image.open(path)
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\PIL\Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'J:/DataSets/Lane/Tusimple\\driver_100_30frame/05251517_
0433.MP4/01650.jpg'`
 i think that the Tusimple dataset should not have any corelation with the CUlane dataset.However,as you can see from the last error information:J:/DataSets/Lane/Tusimple\\driver_100_30frame/05251517_0433.MP4/01650.jpg,the Tusimple's path is strange. i checked out the path of CUlane and Tusimple Dataset is correct.Could you help me ? Any help will be appreciated !
