### ISSUE TITLE
关于训练1920*1080尺寸的Culane数据集

### ISSUE THREAD

**Issue by MengFanZe1** [cfzd/Ultra-Fast-Lane-Detection#162]
您好，我想请教一下，想要训练自己做的1920*1080尺寸的Culane数据集，应该修改哪些文件里的相关参数呀

**Comment by MengFanZe1** [comment]
0%|                                                     | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    train(net, train_loader, loss_dict, optimizer, scheduler,logger, epoch, metric_dict, cfg.use_aux)
  File "train.py", line 59, in train
    for b_idx, data_label in enumerate(progress_bar):
  File "/home/its/anaconda3/envs/mlane/lib/python3.6/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/its/anaconda3/envs/mlane/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
________________ (1920, 1080) (1640, 590)
    return self._process_next_batch(batch)
  File "/home/its/anaconda3/envs/mlane/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/its/anaconda3/envs/mlane/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/its/anaconda3/envs/mlane/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/its/lane/ullane/data/dataset.py", line 73, in __getitem__
    img, label = self.simu_transform(img, label)
  File "/home/its/lane/ullane/data/mytransforms.py", line 19, in __call__
    img, mask = t(img, mask)
  File "/home/its/lane/ullane/data/mytransforms.py", line 71, in __call__
    assert label is None or image.size == label.size
AssertionError

**Comment by cfzd** [comment]
@MengFanZe1 
你是修改了这部分代码吗？
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/dataset.py#L66-L74
理论上来说74行的代码img和label一定是一样大小的，因为都是直接从硬盘上读取的，还没做任何处理的。

如果你想换个分辨率进行训练或者测试，你需要修改这一行代码：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/dataloader.py#L19
修改之后由于输入大小变了，还需要修改一下网络结构，使得FC层的维度和数据一致
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/model/model.py#L60-L64

**Comment by MengFanZe1** [comment]
非常感谢您的解答，我没有修改dataset.py的，发现用的代码为您的老版本，我再更新试一下。再次感谢

**Comment by MengFanZe1** [comment]
您好，我发现是由于我制作Culane数据集时，seg文件夹中的label图尺寸与原图片尺寸不一致导致的，谢谢您的回答。
