### ISSUE TITLE
CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by Firdanis** [cfzd/Ultra-Fast-Lane-Detection#193]
Please, help.
_________________________________________________________________________________________________
(lane-det) firdanis@firdanis-system:~/Ultra-Fast-Lane-Detection$ python -m torch.distributed.launch --nproc_per_node=2 train.py configs/culane.py 
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/firdanis/anaconda3/envs/lane-det/lib/python3.7/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Killing subprocess 27636
Killing subprocess 27637
Traceback (most recent call last):
  File "/home/firdanis/anaconda3/envs/lane-det/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/firdanis/anaconda3/envs/lane-det/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/firdanis/anaconda3/envs/lane-det/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/firdanis/anaconda3/envs/lane-det/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/firdanis/anaconda3/envs/lane-det/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/firdanis/anaconda3/envs/lane-det/bin/python3', '-u', 'train.py', '--local_rank=1', 'configs/culane.py']' returned non-zero exit status 1.

**Comment by cfzd** [comment]
@Firdanis 
It seems a problem with CUDA initialization. Please check the number of GPUs in your machine. If you have one GPU, the `nproc_per_node` should be set to 1.
