### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

### ISSUE THREAD

**Issue by ChrisWang99** [cfzd/Ultra-Fast-Lane-Detection#196]
Traceback (most recent call last):
  File "demo.py", line 30, in <module>
    state_dict = torch.load(cfg.test_model, map_location='cpu')['model']
  File "D:\aanaco\envs\pytorch\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\aanaco\envs\pytorch\lib\site-packages\torch\serialization.py", line 235, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "D:\aanaco\envs\pytorch\lib\site-packages\torch\serialization.py", line 220, in __init__
    _check_seekable(buffer)
  File "D:\aanaco\envs\pytorch\lib\site-packages\torch\serialization.py", line 311, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "D:\aanaco\envs\pytorch\lib\site-packages\torch\serialization.py", line 304, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

运行python demo.py configs/culane.py 会报上面的错
文件我只改了两个位置
data_root = 'D:/Ultra-Fast-Lane-Detection-master/CULANEROOT'
log_path = 'D:/UFdmlogPath'
刚接触python什么都不懂不好意思，还望大佬指点

**Comment by cfzd** [comment]
@ChrisWang99 
 你需要先下载好culane上模型，然后运行
`python demo.py configs/culane.py --test_model /path/to/your/culane/model`
`/path/to/your/culane/model`就是下载的模型的路径

**Comment by ChrisWang99** [comment]
我运行
python demo.py configs/culane.py --test_model /D:/Ultra-Fast-Lane-Detection-master/CULANEROOT
但还是会报错（如下）
(pytorch) D:\Ultra-Fast-Lane-Detection-master\Ultra-Fast-Lane-Detection-master>python demo.py configs/cul
ane.py --test_model /D:/Ultra-Fast-Lane-Detection-master/CULANEROOT
merge  test_model  config
start testing...
Traceback (most recent call last):
  File "demo.py", line 30, in <module>
    state_dict = torch.load(cfg.test_model, map_location='cpu')['model']
  File "D:\aanaco\envs\pytorch\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\aanaco\envs\pytorch\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\aanaco\envs\pytorch\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: '/D:/Ultra-Fast-Lane-Detection-master/CULANEROOT'

因为我是在windows上跑的，请问我的culane解压对了吗，感谢您在百忙之中的答复
![image](https://user-images.githubusercontent.com/32800408/114895021-b617ad80-9e41-11eb-928e-ad4bd4728dbb.png)
![image](https://user-images.githubusercontent.com/32800408/114894582-58836100-9e41-11eb-94b1-bb28821583ef.png)

**Comment by cfzd** [comment]
@ChrisWang99 
`test_model`指的是训练好的网络模型参数文件，不是数据集的路径。你可以使用我们提供的网络模型参数文件，也使用自己训练的模型。如果使用我们提供的网络参数模型，可以在README.md的Trained models那一小节的链接进行下载。然后把这个参数模型文件的路径作为`test_model`的参数来运行demo.py

**Comment by cfzd** [comment]
@ChrisWang99 
还有就是我建议你如果要尝试训练模型，请注释掉`train.py`的147行，也就是cp_projects那一行。

**Comment by ChrisWang99** [comment]
谢谢！我已经成功运行完成了
