### ISSUE TITLE
Training failure

### ISSUE THREAD

**Issue by SiyangXie** [cfzd/Ultra-Fast-Lane-Detection#220]
Hi, I'm trying to train on customized dataset and just encountered this error at the start of training, what could be the possible reason?

```
Traceback (most recent call last):
  File "/home/xiesiyang/workspace/UFLD/train.py", line 144, in <module>
    train(net, train_loader, loss_dict, optimizer, scheduler, logger, epoch, metric_dict, cfg.use_aux)
  File "/home/xiesiyang/workspace/UFLD/train.py", line 66, in train
    loss = calc_loss(loss_dict, results, logger, global_step)
  File "/home/xiesiyang/workspace/UFLD/train.py", line 45, in calc_loss
    loss_cur = loss_dict['op'][i](*datas)
  File "/home/xiesiyang/anaconda3/envs/UFLD/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xiesiyang/anaconda3/envs/UFLD/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 1047, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/xiesiyang/anaconda3/envs/UFLD/lib/python3.9/site-packages/torch/nn/functional.py", line 2693, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/xiesiyang/anaconda3/envs/UFLD/lib/python3.9/site-packages/torch/nn/functional.py", line 2390, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [2, 36, 100, 3]
```

**Comment by reinaldomaslim** [comment]
Hi, I encountered the same error, may i know how to solve this? thanks

**Comment by xings-sdnu** [comment]
change the use_aux to False:`parser.add_argument('--use_aux', default='False', type=str2bool)`
