### ISSUE TITLE
test.py and demo.py can't work

### ISSUE THREAD

**Issue by cedricnam** [cfzd/Ultra-Fast-Lane-Detection#306]
pls help me ! ! !

(lane-det) nam@nam-Nitro-AN515-54:~/kirin/lane-det/Ultra-Fast-Lane-Detection$ python demo.py configs/culane.py --test_model model/culane_18.pth
merge  test_model  config
start testing...
Traceback (most recent call last):
  File "demo.py", line 48, in <module>
    datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms) for split in splits]
  File "demo.py", line 48, in <listcomp>
    datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms) for split in splits]
  File "/home/nam/anaconda3/envs/lane-det/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by cedricnam** [comment]
run demo.py same fault

**Comment by byungjikim** [comment]
I have same issue

**Comment by cfzd** [comment]
@cedricnam 
Sorry, I missed this problem.
@byungjikim 
You need to modify the `data_root` in the config files according to your dataset.
