### ISSUE TITLE
训练报错了，换了一个一样数据就错了，根据提示找不到问题，请教一下大佬,

### ISSUE THREAD

**Issue by qiyuefun** [cfzd/Ultra-Fast-Lane-Detection#309]
Traceback (most recent call last):
  File "train.py", line 187, in <module>
    train(net, train_loader, loss_dict, optimizer, scheduler,logger, epoch, metric_dict, cfg.use_aux)
  File "train.py", line 99, in train
    loss = calc_loss(loss_dict, results, logger, global_step)
  File "train.py", line 62, in calc_loss
    loss_cur = loss_dict['op'][i](*datas)
  File "/home/zkys/anaconda3/envs/ldhtorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zkys/anaconda3/envs/ldhtorch/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/zkys/anaconda3/envs/ldhtorch/lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of size: : [16, 36, 100, 3]

**Comment by qiyuefun** [comment]
python train config/culone.py 就报错了

**Comment by xings-sdnu** [comment]
把--use_aux改为False就可以了：`parser.add_argument('--use_aux', default='False', type=str2bool)`
