### ISSUE TITLE
Traceback (most recent call last):   File "scripts/convert_tusimple.py", line 145, in <module>     names,line_txt = get_tusimple_list(args.root,  ['label_data_0601.json','label_data_0531.json','label_data_0313.json'])   File "scripts/convert_tusimple.py", line 45, in get_tusimple_list     label_json = [json.loads(line) for line in open(l).readlines()] FileNotFoundError: [Errno 2] No such file or directory: '/UFast/TUSIMPLEROOT/label_data_0601.json'

### ISSUE THREAD

**Issue by 5wmy5** [cfzd/Ultra-Fast-Lane-Detection#341]
这是为什么呀

我用的远程服务器，数据集的路径为root/UFast/TUSIMPLEROOT
修改python scripts/convert_tusimple.py --root /UFast/TUSIMPLEROOT运行的结果如下：
Traceback (most recent call last):   
   File "scripts/convert_tusimple.py", line 145, in <module>   
  names,line_txt = get_tusimple_list(args.root,  ['label_data_0601.json','label_data_0531.json','label_data_0313.json'])   
   File "scripts/convert_tusimple.py", line 45, in get_tusimple_list     
       label_json = [json.loads(line) for line in open(l).readlines()] 
FileNotFoundError: [Errno 2] No such file or directory: '/UFast/TUSIMPLEROOT/label_data_0601.json'

**Comment by cfzd** [comment]
@5wmy5 
你有没有tusimple数据集呢？你确定放到`'/UFast/TUSIMPLEROOT/`这个地方了吗？

**Comment by 5wmy5** [comment]
> @5wmy5 你有没有tusimple数据集呢？你确定放到`'/UFast/TUSIMPLEROOT/`这个地方了吗？
已解决：此处已经进入了UFast，所以直接写TUSIMPLEROOT就行不用--root/....
