### ISSUE TITLE
test.py 运行报错：Format of lanes error

### ISSUE THREAD

**Issue by hwang12345** [cfzd/Ultra-Fast-Lane-Detection#347]
使用1080p图像数据集训练模型，训练完成后使用test.py进行测试，运行报错：
merge  test_model  config
merge  test_work_dir  config
start testing...
use_aux:false
init cls
initialize_weights
100%|███████████████████████████████████████████| 49/49 [00:06<00:00,  7.69it/s]
Traceback (most recent call last):
  File "/home/hw/project/LaneDetection/ultra-fast-lane-detection/evaluation/tusimple/lane.py", line 79, in bench_one_submit
    a, p, n = LaneEval.bench(pred_lanes, gt_lanes, y_samples, run_time)
  File "/home/hw/project/LaneDetection/ultra-fast-lane-detection/evaluation/tusimple/lane.py", line 31, in bench
    raise Exception('Format of lanes error.')
Exception: Format of lanes error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 48, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "/home/hw/project/LaneDetection/ultra-fast-lane-detection/evaluation/eval_wrapper.py", line 164, in eval_lane
    res = LaneEval.bench_one_submit(os.path.join(work_dir,exp_name + '.txt'),os.path.join(data_root,'test_label.json'))
  File "/home/hw/project/LaneDetection/ultra-fast-lane-detection/evaluation/tusimple/lane.py", line 81, in bench_one_submit
    raise Exception('Format of lanes error.')
Exception: Format of lanes error.
这个问题应该如何解决？

**Comment by Qiuyanghang** [comment]
> bench_one_submit

你好，请问这个问题怎么解决？
