### ISSUE TITLE
CULane数据集训练完毕后测试出错

### ISSUE THREAD

**Issue by Albertchamberlain** [cfzd/Ultra-Fast-Lane-Detection#353]
merge  test_model  config
merge  test_work_dir  config
merge  test_model  config
merge  test_work_dir  config
start testing...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4335/4335 [04:20<00:00, 16.62it/s]
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test0_normal.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 32777
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test1_crowd.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 28003
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test2_hlight.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 1685
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test3_shadow.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 2876
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test4_noline.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 14021
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test5_arrow.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 3182
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test6_curve.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 1312
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test7_cross.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 0
no positive detection
no ground truth positive
finished process file
precision: -1
recall: -1
Fmeasure: -1
----------------------------------
------------Configuration---------
anno_dir: /root/autodl-tmp/CULane/
detect_dir: ./tmp/culane_eval_tmp/
im_dir: /root/autodl-tmp/CULane/
list_im_file: /root/autodl-tmp/CULane/list/test_split/test8_night.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 21030
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
res_normal 0.0
res_crowd 0.0
res_night 0.0
res_noline 0.0
res_shadow 0.0
res_arrow 0.0
res_hlight 0.0
res_curve 0.0
res_cross -1.0
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "/root/autodl-tmp/TuSimple/Ultra-Fast-Lane-Detection-master/evaluation/eval_wrapper.py", line 163, in eval_lane
    P = TP * 1.0/(TP + FP)
ZeroDivisionError: float division by zero

**Comment by frozenbird07** [comment]
遇到同样问题了，怎么破

**Comment by yangdongang** [comment]
怎么错了
