### ISSUE TITLE
CULane测试出错

### ISSUE THREAD

**Issue by Albertchamberlain** [cfzd/Ultra-Fast-Lane-Detection#357]
训练10个epoch完后进行test出错

Traceback (most recent call last):
  File "test.py", line 48, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "/home/cicero/hbx/Ultra-Fast-Lane-Detection-master/evaluation/eval_wrapper.py", line 147, in eval_lane
    P = TP * 1.0/(TP + FP)
ZeroDivisionError: float division by zero

**Comment by yangdongang** [comment]
请问，你怎么解决的
