### ISSUE TITLE
你好，我在运行test的时候没有输出，但是在运行demo的时候却可以进行识别

### ISSUE THREAD

**Issue by BuridanDonkey** [cfzd/Ultra-Fast-Lane-Detection#366]
Traceback (most recent call last):
  File "D:\Yolov5\entire\Ultra-Fast-Lane-Detection\test.py", line 48, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "D:\Yolov5\entire\Ultra-Fast-Lane-Detection\evaluation\eval_wrapper.py", line 159, in eval_lane
    res = LaneEval.bench_one_submit(os.path.join(work_dir,exp_name + '.txt'),os.path.join(data_root,'test_label.json'))
  File "D:\Yolov5\entire\Ultra-Fast-Lane-Detection\evaluation\tusimple\lane.py", line 63, in bench_one_submit
    raise Exception('We do not get the predictions of all the test tasks')
Exception: We do not get the predictions of all the test tasks

**Comment by AetherLiu** [comment]
请问解决了嘛？问题出在哪呢，我复现其他代码也出现这个问题了
