### ISSUE TITLE
PermissionError: [Errno 13] Permission denied + FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\txt\\out0_normal.txt'

### ISSUE THREAD

**Issue by wohaiyo** [cfzd/Ultra-Fast-Lane-Detection#4]
Hello, when I run your code, there are two problems, help!

Problem 1:

Traceback (most recent call last):
  File "C:\Users\MWG\PycharmProjects\Ultra-Fast-Lane-Detection\utils\config.py", line 95, in _file2dict
    osp.join(temp_config_dir, temp_config_name))
  File "C:\Users\MWG\Anaconda3\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\MWG\\AppData\\Local\\Temp\\tmppmh3002a\\tmp_qc4pvqe.py'

Problem 2:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1.2\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/MWG/PycharmProjects/Ultra-Fast-Lane-Detection/test.py", line 45, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "C:\Users\MWG\PycharmProjects\Ultra-Fast-Lane-Detection\evaluation\eval_wrapper.py", line 137, in eval_lane
    res = call_culane_eval(data_root, 'culane_eval_tmp', work_dir)
  File "C:\Users\MWG\PycharmProjects\Ultra-Fast-Lane-Detection\evaluation\eval_wrapper.py", line 224, in call_culane_eval
    res_all['res_normal'] = read_helper(out0)
  File "C:\Users\MWG\PycharmProjects\Ultra-Fast-Lane-Detection\evaluation\eval_wrapper.py", line 166, in read_helper
    lines = open(path, 'r').readlines()[1:]
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\txt\\out0_normal.txt'

**Comment by cfzd** [comment]
@wohaiyo 
Hi, the first problem seems to be the permission problem. Can you open the file manually?
```
'C:\Users\MWG\AppData\Local\Temp\tmppmh3002a\tmp_qc4pvqe.py'
```
If the file exists and you can open it, try to run pycharm as administrator.


The second problem seems to be the wrong path passed to the code. Did you pass `/tmp` to the code?  It should be
```
python test.py configs/tusimple.py --test_model path_to_tusimple_18.pth --test_work_dir ./tmp
```
It is `./tmp` instead of `/tmp`.

**Comment by wohaiyo** [comment]
Thank you! I solved them.

**Comment by littleserendipity** [comment]
@wohaiyo I meet the same Problem 1 you mentioned above.How did you solve this problem ? Could you say it elaborately ? Thanks for your kindly help !
Here are the errors as follows:
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    args, cfg = merge_config()
  File "E:\LaneCode\Ultra-Fast-Lane-Detection\utils\common.py", line 52, in merge_config
    cfg = Config.fromfile(args.config)
  File "E:\LaneCode\Ultra-Fast-Lane-Detection\utils\config.py", line 159, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "E:\LaneCode\Ultra-Fast-Lane-Detection\utils\config.py", line 85, in _file2dict
    shutil.copyfile(filename,
  File "D:\Miniconda3\envs\pytorch\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\14196\\AppData\\Local\\Temp\\tmpcy90ttx6\\tmpwvroq
sfz.py'

**Comment by wohaiyo** [comment]
@littleserendipity  Please refer to the following link.
https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/39#issuecomment-659490659

**Comment by littleserendipity** [comment]
Thanks a lot,I have sloved this problem by the reference you mentioned above.
