### ISSUE TITLE
demo.py can't work

### ISSUE THREAD

**Issue by SnailDUDUDU** [cfzd/Ultra-Fast-Lane-Detection#68]
您好，我在运行demo时遇见了以下问题，自己查资料也没有解决，您可以给看一下吗（我在pycharm的terminal里面运行：python demo.py configs/culane.py --test_model path_to_culane_18.pth）

(lane-det) D:\Ultra-Fast-Lane-Detection-master>python demo.py configs/culane.py --test_model path_to_culane_18.pth
Traceback (most recent call last):
  File "D:\Ultra-Fast-Lane-Detection-master\utils\config.py", line 86, in _file2dict
    osp.join(temp_config_dir, temp_config_name))
  File "D:\annaconda\envs\lane-det\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\zss\\AppData\\Local\\Temp\\tmp20nybokr\\tmpev6zrrnd.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    args, cfg = merge_config()
  File "D:\Ultra-Fast-Lane-Detection-master\utils\common.py", line 50, in merge_config
    cfg = Config.fromfile(args.config)
  File "D:\Ultra-Fast-Lane-Detection-master\utils\config.py", line 159, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "D:\Ultra-Fast-Lane-Detection-master\utils\config.py", line 99, in _file2dict
    temp_config_file.close()
  File "D:\annaconda\envs\lane-det\lib\tempfile.py", line 807, in __exit__
    self.cleanup()
  File "D:\annaconda\envs\lane-det\lib\tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)
  File "D:\annaconda\envs\lane-det\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\annaconda\envs\lane-det\lib\shutil.py", line 404, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "D:\annaconda\envs\lane-det\lib\shutil.py", line 402, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] 目录不是空的。: 'C:\\Users\\zss\\AppData\\Local\\Temp\\tmp20nybokr'

**Comment by zchrissirhcz** [comment]
确认一下，代码是不是最新的。最近几天有更新windows相关支持。

**Comment by SnailDUDUDU** [comment]
好的！多谢您的回复，我更新一下代码试试。










在 2020-08-12 16:57:29，"Zhuo Zhang" <notifications@github.com> 写道：

确认一下，代码是不是最新的。最近几天有更新windows相关支持。
