### ISSUE TITLE
Trying to run demo.py in my own images

### ISSUE THREAD

**Issue by italovinicius18** [cfzd/Ultra-Fast-Lane-Detection#82]
Hello, i'm trying to run demo.py with my own data,i already changed the path to the images and datasets are recognizing my images and storaging them, but i getting error
```shell
$ `python` .\demo.py configs/tusimple.py --test_model .\tusimple_18.pth
merge  test_model  config
start testing...
test.avi
  0%|                                    | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File ".\demo.py", line 63, in <module>
    for i, data in enumerate(tqdm.tqdm(loader)):
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\tqdm\std.py", line 1130, in __iter__
    for obj in iterable:
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\italo\Documents\Proj. Pesq. Carros Autônomos\Lane detection\Ultra-Fast-Lane-Detection\data\dataset.py", line 27, in __getitem__
    img = loader_func(img_path)
  File "C:\Users\italo\Documents\Proj. Pesq. Carros Autônomos\Lane detection\Ultra-Fast-Lane-Detection\data\dataset.py", line 11, in loader_func
    return Image.open(path)
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\PIL\Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
ValueError: embedded null character
```

The images are in 1280x720 and datasets have them, i made a test.txt with the names os img files

**Comment by cfzd** [comment]
@italovinicius18 
Sorry for the late response. It seems the path is not valid, could you check the path in here?
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/1a88868fd382dd8154cd9b79de09b676f5d47c2b/data/dataset.py#L27

**Comment by italovinicius18** [comment]
Thanks, i fixed this problem, but i've got another

```shell
Traceback (most recent call last):
  File ".\demo_carla.py", line 76, in <module>
    out = net(imgs)
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\italo\Documents\Proj. Pesq. Carros Autônomos\Lane detection\Ultra-Fast-Lane-Detection\model\model.py", line 76, in forward
    x2,x3,fea = self.model(x)
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\italo\Documents\Proj. Pesq. Carros Autônomos\Lane detection\Ultra-Fast-Lane-Detection\model\backbone.py", line 48, in forward
    x = self.conv1(x)
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\italo\anaconda3\envs\lane-det\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 720, 1280, 3] to have 3 channels, but got 720 channels instead
```
