### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by Kaimingfan** [cfzd/Ultra-Fast-Lane-Detection#97]
你好，请问一下tusimple数据集里面的test.txt文件是什么？

Traceback (most recent call last):
  File "test.py", line 48, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "/root/Ultra-Fast-Lane-Detection/evaluation/eval_wrapper.py", line 155, in eval_lane
    run_test_tusimple(net, data_root, work_dir, exp_name, griding_num, use_aux, distributed)
  File "/root/Ultra-Fast-Lane-Detection/evaluation/eval_wrapper.py", line 88, in run_test_tusimple
    loader = get_test_loader(batch_size,data_root,'Tusimple', distributed)
  File "/root/Ultra-Fast-Lane-Detection/data/dataloader.py", line 69, in get_test_loader
    test_dataset = LaneTestDataset(data_root,os.path.join(data_root, 'test.txt'), img_transform = img_transforms)
  File "/root/Ultra-Fast-Lane-Detection/data/dataset.py", line 19, in __init__
    with open(list_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/remote-home/my/tusimple/test.txt'

**Comment by cfzd** [comment]
@Kaimingfan 
As written in `INSTALL.md`, you might need to run this:
```
python scripts/convert_tusimple.py --root $TUSIMPLEROOT
# this will generate segmentations and two list files: train_gt.txt and test.txt
```

**Comment by Kaimingfan** [comment]
请问哪里能找到test_tasks_0627.json

**Comment by Kaimingfan** [comment]
我找到了
